export const students = [
    {
        code: "1",
        name: "Ahmed Ali",
        year: "الفرقة الأولى",
        subjects: ["Math", "Physics", "CS"],
        gpa: 3.2,
        status: "منتظم",
        attendance: "92%",
        skills: ["C Programming", "Problem Solving"],
        email: "ahmed.ali@univ.edu",
        phone: "01012345678",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
    },
    {
        code: "2",
        name: "Mohamed Hassan",
        year: "الفرقة الأولى",
        subjects: ["English", "Math"],
        gpa: 2.6,
        status: "متوسط",
        attendance: "85%",
        skills: ["Communication"],
        email: "mohamed.hassan@univ.edu",
        phone: "01123456789",
        image: "https://randomuser.me/api/portraits/men/2.jpg",
    },
    {
        code: "3",
        name: "Omar Youssef",
        year: "الفرقة الثانية",
        subjects: ["Data Structures", "OOP"],
        gpa: 3.7,
        status: "متفوق",
        attendance: "96%",
        skills: ["Java", "Algorithms"],
        email: "omar.youssef@univ.edu",
        phone: "01234567890",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
    },
    {
        code: "4",
        name: "Mahmoud Said",
        year: "الفرقة الثانية",
        subjects: ["Databases", "Web"],
        gpa: 3.0,
        status: "منتظم",
        attendance: "90%",
        skills: ["SQL", "HTML", "CSS"],
        email: "mahmoud.said@univ.edu",
        phone: "01098765432",
        image: "https://randomuser.me/api/portraits/men/4.jpg",
    },
    {
        code: "5",
        name: "Mostafa Adel",
        year: "الفرقة الثالثة",
        subjects: ["AI", "Machine Learning"],
        gpa: 3.9,
        status: "متفوق",
        attendance: "98%",
        skills: ["Python", "ML"],
        email: "mostafa.adel@univ.edu",
        phone: "01187654321",
        image: "https://randomuser.me/api/portraits/men/5.jpg",
    },
    {
        code: "6",
        name: "Youssef Magdy",
        year: "الفرقة الثالثة",
        subjects: ["Networks", "Security"],
        gpa: 3.1,
        status: "منتظم",
        attendance: "91%",
        skills: ["Networking"],
        email: "youssef.magdy@univ.edu",
        phone: "01222223333",
        image: "https://randomuser.me/api/portraits/men/6.jpg",
    },
    {
        code: "7",
        name: "Karim Nabil",
        year: "الفرقة الرابعة",
        subjects: ["Cloud", "DevOps"],
        gpa: 3.5,
        status: "متفوق",
        attendance: "94%",
        skills: ["Docker", "AWS"],
        email: "karim.nabil@univ.edu",
        phone: "01033334444",
        image: "https://randomuser.me/api/portraits/men/7.jpg",
    },
    {
        code: "8",
        name: "Hassan Tarek",
        year: "الفرقة الرابعة",
        subjects: ["Graduation Project"],
        gpa: 2.9,
        status: "منتظم",
        attendance: "88%",
        skills: ["Research"],
        email: "hassan.tarek@univ.edu",
        phone: "01144445555",
        image: "https://randomuser.me/api/portraits/men/8.jpg",
    },
    {
        code: "9",
        name: "Ali Fathy",
        year: "الفرقة الأولى",
        subjects: ["Math", "Programming"],
        gpa: 3.0,
        status: "منتظم",
        attendance: "89%",
        skills: ["Python Basics"],
        email: "ali.fathy@univ.edu",
        phone: "01255556666",
        image: "https://randomuser.me/api/portraits/men/9.jpg",
    },
    {
        code: "10",
        name: "Ibrahim Ashraf",
        year: "الفرقة الثانية",
        subjects: ["Algorithms", "OOP"],
        gpa: 3.4,
        status: "منتظم",
        attendance: "93%",
        skills: ["C++"],
        email: "ibrahim.ashraf@univ.edu",
        phone: "01066667777",
        image: "https://randomuser.me/api/portraits/men/10.jpg",
    },

    {
        code: "11",
        name: "Ahmed Samy",
        year: "الفرقة الأولى",
        subjects: ["IT", "Math"],
        gpa: 2.8,
        status: "متوسط",
        attendance: "84%",
        skills: ["IT Support"],
        email: "ahmed.samy@univ.edu",
        phone: "01177778888",
        image: "https://randomuser.me/api/portraits/men/11.jpg",
    },
    {
        code: "12",
        name: "Mohamed Adel",
        year: "الفرقة الثانية",
        subjects: ["Databases", "SQL"],
        gpa: 3.3,
        status: "منتظم",
        attendance: "90%",
        skills: ["MySQL"],
        email: "mohamed.adel@univ.edu",
        phone: "01288889999",
        image: "https://randomuser.me/api/portraits/men/12.jpg",
    },
    {
        code: "13",
        name: "Omar Salah",
        year: "الفرقة الثالثة",
        subjects: ["React", "Node"],
        gpa: 3.6,
        status: "متفوق",
        attendance: "95%",
        skills: ["React", "Node.js"],
        email: "omar.salah@univ.edu",
        phone: "01099990000",
        image: "https://randomuser.me/api/portraits/men/13.jpg",
    },
    {
        code: "14",
        name: "Mahmoud Gamal",
        year: "الفرقة الرابعة",
        subjects: ["Project Management"],
        gpa: 3.1,
        status: "منتظم",
        attendance: "90%",
        skills: ["Leadership"],
        email: "mahmoud.gamal@univ.edu",
        phone: "01112121212",
        image: "https://randomuser.me/api/portraits/men/14.jpg",
    },
    {
        code: "15",
        name: "Mostafa Samir",
        year: "الفرقة الأولى",
        subjects: ["Programming", "Logic"],
        gpa: 2.7,
        status: "متوسط",
        attendance: "83%",
        skills: ["Logic"],
        email: "mostafa.samir@univ.edu",
        phone: "01213131313",
        image: "https://randomuser.me/api/portraits/men/15.jpg",
    },

    {
        code: "16",
        name: "Youssef Ali",
        year: "الفرقة الثانية",
        subjects: ["OS", "Computer Architecture"],
        gpa: 3.2,
        status: "منتظم",
        attendance: "91%",
        skills: ["Linux"],
        email: "youssef.ali@univ.edu",
        phone: "01014141414",
        image: "https://randomuser.me/api/portraits/men/16.jpg",
    },
    {
        code: "17",
        name: "Karim Ashraf",
        year: "الفرقة الثالثة",
        subjects: ["Cyber Security"],
        gpa: 3.8,
        status: "متفوق",
        attendance: "97%",
        skills: ["Penetration Testing"],
        email: "karim.ashraf@univ.edu",
        phone: "01115151515",
        image: "https://randomuser.me/api/portraits/men/17.jpg",
    },
    {
        code: "18",
        name: "Hassan Ali",
        year: "الفرقة الرابعة",
        subjects: ["Graduation Project"],
        gpa: 2.9,
        status: "منتظم",
        attendance: "88%",
        skills: ["Documentation"],
        email: "hassan.ali@univ.edu",
        phone: "01216161616",
        image: "https://randomuser.me/api/portraits/men/18.jpg",
    },
    {
        code: "19",
        name: "Ali Mohamed",
        year: "الفرقة الأولى",
        subjects: ["Math", "IT"],
        gpa: 2.5,
        status: "متوسط",
        attendance: "80%",
        skills: ["Basics"],
        email: "ali.mohamed@univ.edu",
        phone: "01017171717",
        image: "https://randomuser.me/api/portraits/men/19.jpg",
    },
    {
        code: "20",
        name: "Ibrahim Hassan",
        year: "الفرقة الثانية",
        subjects: ["Data Analysis"],
        gpa: 3.4,
        status: "منتظم",
        attendance: "92%",
        skills: ["Excel", "Python"],
        email: "ibrahim.hassan@univ.edu",
        phone: "01118181818",
        image: "https://randomuser.me/api/portraits/men/20.jpg",
    },

    {
        code: "21",
        name: "Ahmed Fathy",
        year: "الفرقة الثالثة",
        subjects: ["AI", "Deep Learning"],
        gpa: 3.9,
        status: "متفوق",
        attendance: "98%",
        skills: ["TensorFlow"],
        email: "ahmed.fathy@univ.edu",
        phone: "01219191919",
        image: "https://randomuser.me/api/portraits/men/21.jpg",
    },
    {
        code: "22",
        name: "Mohamed Tamer",
        year: "الفرقة الرابعة",
        subjects: ["Cloud Computing"],
        gpa: 3.3,
        status: "منتظم",
        attendance: "91%",
        skills: ["Azure"],
        email: "mohamed.tamer@univ.edu",
        phone: "01020202020",
        image: "https://randomuser.me/api/portraits/men/22.jpg",
    },
    {
        code: "23",
        name: "Omar Adel",
        year: "الفرقة الأولى",
        subjects: ["Programming Basics"],
        gpa: 2.8,
        status: "منتظم",
        attendance: "86%",
        skills: ["C Basics"],
        email: "omar.adel@univ.edu",
        phone: "01121212121",
        image: "https://randomuser.me/api/portraits/men/23.jpg",
    },
    {
        code: "24",
        name: "Mahmoud Ashraf",
        year: "الفرقة الثانية",
        subjects: ["Web Design"],
        gpa: 3.1,
        status: "منتظم",
        attendance: "89%",
        skills: ["UI/UX"],
        email: "mahmoud.ashraf@univ.edu",
        phone: "01222222222",
        image: "https://randomuser.me/api/portraits/men/24.jpg",
    },
    {
        code: "25",
        name: "Mostafa Hassan",
        year: "الفرقة الثالثة",
        subjects: ["Mobile Development"],
        gpa: 3.5,
        status: "متفوق",
        attendance: "94%",
        skills: ["Flutter"],
        email: "mostafa.hassan@univ.edu",
        phone: "01023232323",
        image: "https://randomuser.me/api/portraits/men/25.jpg",
    },

    {
        code: "26",
        name: "Youssef Samy",
        year: "الفرقة الرابعة",
        subjects: ["Software Engineering"],
        gpa: 3.4,
        status: "منتظم",
        attendance: "92%",
        skills: ["UML"],
        email: "youssef.samy@univ.edu",
        phone: "01124242424",
        image: "https://randomuser.me/api/portraits/men/26.jpg",
    },
    {
        code: "27",
        name: "Karim Mohamed",
        year: "الفرقة الأولى",
        subjects: ["Math", "Logic"],
        gpa: 2.9,
        status: "منتظم",
        attendance: "87%",
        skills: ["Logical Thinking"],
        email: "karim.mohamed@univ.edu",
        phone: "01225252525",
        image: "https://randomuser.me/api/portraits/men/27.jpg",
    },
    {
        code: "28",
        name: "Hassan Samir",
        year: "الفرقة الثانية",
        subjects: ["Networks"],
        gpa: 3.0,
        status: "منتظم",
        attendance: "90%",
        skills: ["Routing"],
        email: "hassan.samir@univ.edu",
        phone: "01026262626",
        image: "https://randomuser.me/api/portraits/men/28.jpg",
    },
    {
        code: "29",
        name: "Ali Ashraf",
        year: "الفرقة الثالثة",
        subjects: ["Front-End"],
        gpa: 3.6,
        status: "متفوق",
        attendance: "95%",
        skills: ["React", "CSS"],
        email: "ali.ashraf@univ.edu",
        phone: "01127272727",
        image: "https://randomuser.me/api/portraits/men/29.jpg",
    },
    {
        code: "30",
        name: "Ibrahim Samir",
        year: "الفرقة الرابعة",
        subjects: ["Back-End"],
        gpa: 3.5,
        status: "منتظم",
        attendance: "93%",
        skills: ["Node.js", "APIs"],
        email: "ibrahim.samir@univ.edu",
        phone: "01228282828",
        image: "https://randomuser.me/api/portraits/men/30.jpg",
    },
];
